server:
  port: 8082

spring:
  application:
    name: storage-service

  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 55MB
      file-size-threshold: 2KB

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}

minio:
  url: ${MINIO_URL}
  access-key: ${MINIO_ACCESS_KEY}
  secret-key: ${MINIO_SECRET_KEY}
  bucket: ${MINIO_BUCKET}

metadata:
  service-url: ${METADATA_SERVICE_URL}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.web: INFO