server:
  port: 8080
  http2:
    enabled: false
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:5173"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true
jwt:
  secret: c2Vlbm1lZXR0cnllbmVteWFwcGxlbm90ZXN3aW5nbG9zdGdyYXNzeWVzZmlmdHlzZW4=
